### ISSUE TITLE
Non-code contributions

### ISSUE THREAD

**Issue by johnbillion** [markoheijnen/WordPress-contributions#10]
I'm always conscious of the fact that there are many people who contribute to WordPress without contributing code. For example, people who answer endless support questions in the support forums, people who help organise or speak at WordCamps, and people who contribute to the Codex and the Developer Handbook.

We might be able to work with the folks at WordPress.org to see if we can get stats for things like support forum and Codex contributions. Developer Handbook contributions would be fairly simple too as it's just a custom post type on the Make blog. WordCamp organisers or speakers would be the difficult one.

**Comment by bueltge** [comment]
Also a lot of people help other people on forums, like [WPSE](http://wordpress.stackexchange.com/). The contributing part inside the community is also a big issue for the life and high of WordPress.

**Comment by markoheijnen** [comment]
For translating WordPress I do have a ticket since I can write that code. I'm curious if we can do something cool for support forums and WordCamps. I guess for WordCamps it's still something you can do yourself but I can see why that one would be hard.

@johnbillion: What do you want to see more for Codex contributions. There is already a widget for that so I guess you are missing something.

@bueltge: WPSE was mentioned in my blog post. Still need to look into the API and see what data can be used.

**Comment by bueltge** [comment]
Great to see, that also Non-Coder get a praise in your plugin.

**Comment by markoheijnen** [comment]
If there are API's I can use then I will use them ;)

**Comment by bueltge** [comment]
SA API: http://api.stackexchange.com/
How To, maybe helpful: http://devzone.zend.com/1837/using-the-stack-exchange-api-with-php-part-1/
